/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import javax.swing.DefaultListModel;
import javax.swing.event.DocumentEvent;
import project.Entity.Word;
import project.management.DictionaryManagement;
import project.management.SQLiteJDBCDriverConnection;
import javax.swing.event.DocumentListener;
import java.util.*;
import javax.swing.JTextField;
/**
 *
 * @author Liscli
 */

public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        management  = new DictionaryManagement();    
        model = new DefaultListModel();
        currentList = new LinkedList<>();
        //
        fillList();
        //
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchPanel = new javax.swing.JPanel();
        searchTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        vocabuList = new javax.swing.JList<>();
        deffinitionPanel = new javax.swing.JPanel();
        wordField = new javax.swing.JTextField();
        soundButton = new javax.swing.JButton();
        setButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        deffinitionTextPanel = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchPanel.setBackground(new java.awt.Color(204, 204, 204));

        searchTextField.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        searchTextField.setText("Search . . .");
        searchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextFieldActionPerformed(evt);
            }
        });

        vocabuList.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        vocabuList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        vocabuList.setFixedCellWidth(0);
        vocabuList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vocabuListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(vocabuList);

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                .addContainerGap())
        );

        searchTextField.getDocument().addDocumentListener(new DocumentListener() {

            public void insertUpdate(DocumentEvent e) {
                //
                search();
            }
            public void removeUpdate(DocumentEvent e) {
                // doSomething();
                search();
            }
            public void changedUpdate(DocumentEvent e) {
                //doSomething();
                search();

            }
        });

        getContentPane().add(searchPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        deffinitionPanel.setBackground(new java.awt.Color(153, 153, 153));

        wordField.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        wordField.setText(". . .");

        soundButton.setText("jButton1");
        soundButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundButtonActionPerformed(evt);
            }
        });

        setButton.setText("jButton2");

        deffinitionTextPanel.setContentType("text/html"); // NOI18N
        jScrollPane3.setViewportView(deffinitionTextPanel);
        deffinitionTextPanel.setEditable(false);

        javax.swing.GroupLayout deffinitionPanelLayout = new javax.swing.GroupLayout(deffinitionPanel);
        deffinitionPanel.setLayout(deffinitionPanelLayout);
        deffinitionPanelLayout.setHorizontalGroup(
            deffinitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deffinitionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deffinitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(deffinitionPanelLayout.createSequentialGroup()
                        .addComponent(wordField, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(soundButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        deffinitionPanelLayout.setVerticalGroup(
            deffinitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deffinitionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deffinitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soundButton)
                    .addComponent(setButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                .addContainerGap())
        );

        wordField.setEditable(false);

        getContentPane().add(deffinitionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 1, 480, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void soundButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundButtonActionPerformed
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_soundButtonActionPerformed

    private void vocabuListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vocabuListMouseClicked
        // TODO add your handling code here:
        int id = vocabuList.getSelectedIndex();
        Word w = currentList.get(id);
        wordField.setText(w.getTarget());
        deffinitionTextPanel.setText(w.getExplain());
    }//GEN-LAST:event_vocabuListMouseClicked

    private void searchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextFieldActionPerformed
    private boolean compare(String search,String var){
        if(search.length() > var.length()) return false; 
        for(int i=0;i<Math.min(search.length(), var.length());i++){
            if( (search.charAt(i)!=var.charAt(i)) ) return false;
        }
        return true;
    }
    //
    private void fillList(){
        model.clear();
        vocabuList.setModel(model);
        //
        int id = 0;
        for(Word var : management.getDictionary().getAllWords()){
            model.add(id++,var.getTarget());
            currentList.add(var);  
        }
    }
    private void search(){
        //vocabuList.setModel(model);
        model.clear();
        currentList.clear();
        String s = searchTextField.getText();
        int id = 0;
        for(Word var : management.getDictionary().getAllWords()){
            if(compare(s,var.getTarget())){
            model.add(id++,var.getTarget());
            currentList.add(var);
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
//SwingUtilities.updateComponentTreeUI(frame);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel deffinitionPanel;
    private javax.swing.JTextPane deffinitionTextPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JButton setButton;
    private javax.swing.JButton soundButton;
    private javax.swing.JList<String> vocabuList;
    private javax.swing.JTextField wordField;
    // End of variables declaration//GEN-END:variables
    private DictionaryManagement management;    
    private DefaultListModel model;
    private List<Word> currentList;
}
